# Generated by Django 5.2.17 on 2026-10-01 14:45

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("inspire_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("arxiv_id", models.CharField(blank=True, max_length=32, null=True)),
                ("title", models.TextField()),
                ("collaboration", models.CharField(blank=True, max_length=200)),
                ("earliest_date", models.DateField()),
                ("hepdata_record_id", models.IntegerField(blank=True, null=True)),
                ("hepdata_record_doi", models.CharField(blank=True, max_length=100)),
                ("hepdata_version", models.IntegerField(blank=True, null=True)),
                ("readiness_score", models.FloatField(blank=True, null=True)),
                ("extraction_version", models.CharField(blank=True, max_length=64)),
                ("last_extracted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("harvested", "Harvested"),
                            ("no_arxiv_id", "No Arxiv Id"),
                            ("no_latex", "No Latex"),
                            ("source_error", "Source Error"),
                            ("filter_error", "Filter Error"),
                            ("extraction_error", "Extraction Error"),
                            ("extracted", "Extracted"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="harvested",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["earliest_date"], name="paper_date_idx"),
                    models.Index(fields=["readiness_score"], name="paper_readiness_idx"),
                    models.Index(fields=["hepdata_record_id"], name="paper_hepdata_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeclaredProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("cross_section", "cross_section"),
                            ("upper_limit", "upper_limit"),
                            ("efficiency_map", "efficiency_map"),
                            ("likelihood", "likelihood"),
                            ("covariance_matrix", "covariance_matrix"),
                            ("acceptance_table", "acceptance_table"),
                            ("cutflow", "cutflow"),
                            ("correlation_matrix", "correlation_matrix"),
                            ("other", "other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence_span", models.TextField()),
                ("evidence_section", models.TextField()),
                ("evidence_kind", models.CharField(blank=True, max_length=32)),
                ("confidence", models.FloatField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("fingerprint", models.CharField(max_length=64)),
                ("is_current", models.BooleanField(default=True)),
                ("extraction_version", models.CharField(max_length=64)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("merged_duplicates", models.IntegerField(default=0)),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="inspire_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="radar.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishedTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hepdata_record_id", models.IntegerField()),
                ("table_doi", models.CharField(max_length=120, unique=True)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("table", "Table"), ("resource", "Resource")],
                        default="table",
                        max_length=16,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["hepdata_record_id"], name="table_record_idx"),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="table_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Gap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("uncertain", "Uncertain"),
                            ("missing", "Missing"),
                            ("no_record", "No Record"),
                        ],
                        max_length=16,
                    ),
                ),
                ("severity", models.SmallIntegerField()),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("embedding_similarity", models.FloatField(blank=True, null=True)),
                ("caption_overlap", models.FloatField(blank=True, null=True)),
                ("reconcile_version", models.CharField(max_length=16)),
                (
                    "declared_product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap",
                        to="radar.declaredproduct",
                    ),
                ),
                (
                    "matched_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gaps",
                        to="radar.publishedtable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[("accept", "Accept"), ("reject", "Reject")], max_length=16
                    ),
                ),
                ("reviewer", models.CharField(max_length=150)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="radar.declaredproduct",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="declaredproduct",
            index=models.Index(fields=["product_type"], name="product_type_idx"),
        ),
        migrations.AddIndex(
            model_name="declaredproduct",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="product_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="declaredproduct",
            constraint=models.UniqueConstraint(
                fields=("paper", "fingerprint"), name="product_fingerprint_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="declaredproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="product_conf_range",
            ),
        ),
        migrations.AddIndex(
            model_name="gap",
            index=models.Index(
                condition=models.Q(("status", "published"), _negated=True),
                fields=["-severity", "status"],
                name="gap_triage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gap",
            index=models.Index(fields=["status"], name="gap_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="gap",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity__gte", 0), ("severity__lte", 3)),
                name="gap_severity_range",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["declared_product", "-created_at"], name="review_product_idx"
            ),
        ),
    ]
