# Generated by Django 5.2.17 on 2026-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='processing_status',
            field=models.CharField(choices=[('harvested', 'Harvested'), ('no_arxiv_id', 'No Arxiv Id'), ('no_latex', 'No Latex'), ('source_error', 'Source Error'), ('filter_error', 'Filter Error'), ('extraction_error', 'Extraction Error'), ('extracted', 'Extracted'), ('reconcile_error', 'Reconcile Error'), ('reconciled', 'Reconciled')], default='harvested', max_length=32),
        ),
    ]
